### ISSUE TITLE
Validate scan_sudoers module in your environment

### ISSUE THREAD

**Issue by ahuffman** [ahuffman/ansible-role-scan-sudoers#3]
Hi @gforster can you please try out the latest commit in your environment and let me know if we were able to parse everything.  I had to write a heck of a regex to handle all the variants of a user specification.

Also I'm handling default override rules as user_specifications, since they don't really fit into the category of an Alias.  I was also wondering if it made sense to move the default override rules to the defaults dictionary, but that was more intended to handle pure `Defaults [param]` entries while trying to stick to the variable structures of wtcross/ansible-sudoers.

Based on what I've put together for this project I'm probably going to go back and make some changes to the wtcross/ansible-sudoers role so we can use this to pull a config off of a system and theoretically lay down a configuration on another system from what we captured (i.e. migrate running sudoers config to another system).

**Comment by gforster** [comment]
Checked against a few hundred linux and AIX servers with various configs - some with straight /etc/sudoers, some utilizing /etc/sudoers.d/<individual_files>, some with specific /etc/sudoers.local files, some with various combinations....and it all seems to check out!

I can see this enabling a few different use cases - 1:1 migrations, remediating existing hosts that haven't yet been part of something like wtcros/ansible-sudoers, creating and managing a centralized sudoers file, or even in preparation to move sudoers to LDAP.  Much appreciated. 

as far as the default override rules...they really are almost their own category aren't they? But, it works fine as is. I don't know that the defaults dict is the best place without some other flag in there indicating it as different. Maybe.

**Comment by ahuffman** [comment]
@gforster I added a few more things today, not sure which commit you tested with.  Basically yesterday I added support for single-line multiple alias entries.  Today I added support for selinux and solaris privileges.  I also drastically cleaned up the output today so we are only displaying values that we've parsed vs. every possible field (with empty values).  I added a couple of module params yesterday as well that allow for turning off different parts of the output if desired.  I'm still digging through the documentation on sudoers to see if there's any other edge cases i've missed, but i think it's looking awesome at this point.

**Comment by gforster** [comment]
For the most part, this is great! Very useful and clean. 

For some reason, it is now hanging on AIX. Works great on any linux system I've tested (SLES, Red Hat, Ubuntu). Not sure what's up with AIX yet. The last few lines when doing ANSIBLE_DEBUG=1 are:
```
 30816 1552702368.27999: ANSIBALLZ: Using lock for scan_sudoers
 30816 1552702368.28003: ANSIBALLZ: Acquiring lock
 30816 1552702368.28008: ANSIBALLZ: Lock acquired: 140064549024848
 30816 1552702368.28012: ANSIBALLZ: Creating module
 30816 1552702368.37758: ANSIBALLZ: Writing module
 30816 1552702368.37787: ANSIBALLZ: Renaming module
 30816 1552702368.37795: ANSIBALLZ: Done creating module
 30816 1552702368.37839: _low_level_execute_command(): starting
 30816 1552702368.37847: _low_level_execute_command(): executing: /bin/sh -c '/usr/bin/python && sleep 0'
 30816 1552702368.38312: Sending initial data
 30816 1552702368.39814: Sent initial data (74534 bytes)
````

**Comment by gforster** [comment]
OK...was able to get it to run one of the minimal output tasks and it is failing with `KeyError: 'included_files'`

These servers are using /etc/sudoers and don't have #include or #includedirs

```
Using module file /app/ansible-playbooks/library/scan_sudoers
<myaixtestserver> ESTABLISH SSH CONNECTION FOR USER: None
<myaixtestserver> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ServerAliveInterval=10 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/828d88fe4f myaixtestserver '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<myaixtestserver> (1, '', 'Traceback (most recent call last):\n  File "<stdin>", line 113, in <module>\n  File "<stdin>", line 105, in _ansiballz_main\n  File "<stdin>", line 48, in invoke_module\n  File "/tmp/ansible_scan_sudoers_payload_7l67od/__main__.py", line 572, in <module>\n  File "/tmp/ansible_scan_sudoers_payload_7l67od/__main__.py", line 565, in main\n  File "/tmp/ansible_scan_sudoers_payload_7l67od/__main__.py", line 545, in get_sudoers_configs\nKeyError: \'included_files\'\n')
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_scan_sudoers_payload_7l67od/__main__.py", line 572, in <module>
  File "/tmp/ansible_scan_sudoers_payload_7l67od/__main__.py", line 565, in main
  File "/tmp/ansible_scan_sudoers_payload_7l67od/__main__.py", line 545, in get_sudoers_configs
KeyError: 'included_files'

fatal: [myaixtestserver]: FAILED! => {
    "changed": false, 
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_scan_sudoers_payload_7l67od/__main__.py", line 572, in <module>
  File "/tmp/ansible_scan_sudoers_payload_7l67od/__main__.py", line 565, in main
  File "/tmp/ansible_scan_sudoers_payload_7l67od/__main__.py", line 545, in get_sudoers_configs
KeyError: 'included_files'
```

**Comment by ahuffman** [comment]
@gforster Awesome, I appreciate the assistance testing.  That was probably the only thing I didn't test for haha.  Easy fix.  I opened (and closed) a separate issue #4 for that, and pushed up a fix.  If you have a chance today let me know how the updated code works on the machines that were having problems last week.  Thanks!

**Comment by gforster** [comment]
Tested - all works! Thank you!

**Comment by ahuffman** [comment]
Thanks @gforster.  I'm going to close this testing issue out now, since I think we've covered just about everything.  Feel free to open any new issues you come across, because I do not currently have an extensive (multi-OS) testing environment, and I'm sure you'll hit the issues before I do.  I'm planning on building some molecule tests out eventually with some CI/CD processes, but until then...
